Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2020-03, with the labels that each got.

#24 Changes from testing before first release
  deploy/kubernetes/csi-attacher-nfsplugin.yaml
  deploy/kubernetes/csi-attacher-rbac.yaml
  deploy/kubernetes/csi-nfs-driverinfo.yaml
  deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml
  pkg/nfs/nfs.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#29 Add .prow.sh to enable prow jobs
  .prow.sh
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#28 Change base image to centos:latest
  Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#26 Rename driver to follow CSI plugin naming conventions
  deploy/kubernetes/csi-nfs-driverinfo.yaml
  examples/kubernetes/nginx.yaml
  pkg/nfs/nfs.go
  test/nfs-testdriver.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note, size/XS

#27 Add basic info to README about the plugin compatibility and features
  README.md
  deploy/kubernetes/csi-nodeplugin-nfsplugin.yaml
  pkg/nfs/nfs.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/M

#15 Add more access modes to volume capabilities
  pkg/nfs/nfs.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S
