Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2020-10, with the labels that each got.

#56 Add example for NFS provisioner
  examples/kubernetes/nfs-provisioner/README.md
  examples/kubernetes/nfs-provisioner/nfs-server-lb.yaml
  examples/kubernetes/nfs-provisioner/nfs-server.yaml
  examples/kubernetes/nfs-provisioner/pv-nfs-csi.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/L

#58 fix: broken manifest for `nfs-server.yaml`
  examples/kubernetes/nfs-provisioner/nfs-server-lb.yaml
  examples/kubernetes/nfs-provisioner/nfs-server.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#59 docs: Use `itsthenetwork/nfs-server-alpine` for NFS server provisioning
  examples/kubernetes/nfs-provisioner/README.md
  examples/kubernetes/nfs-provisioner/app.yaml
  examples/kubernetes/nfs-provisioner/nfs-server-lb.yaml
  examples/kubernetes/nfs-provisioner/nfs-server.yaml
  examples/kubernetes/nfs-provisioner/pv-nfs-csi.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/L

#60 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#57 Add manifest for installing driver controller and install docs
  .gitignore
  Makefile
  deploy/kubernetes/csi-nfs-controller.yaml
  deploy/kubernetes/rbac-csi-nfs-controller.yaml
  docs/csi-dev.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, release-note-none, size/L

#62 CI: Add GH Actions for sanity tests
  .github/workflows/sanity.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#63 CI: update GH Actions for sanity-test
  .github/workflows/sanity.yaml
  test/sanity/params.yaml
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#66 Add symlink for cloudbuild.yaml and .cloudbuild.sh
  .cloudbuild.sh
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#61 doc: update NFS provisioner example
  deploy/kubernetes/csi-nfs-node.yaml
  examples/kubernetes/nfs-provisioner/nfs-server.yaml
  examples/kubernetes/nfs-server/README.md
  examples/kubernetes/nfs-server/deployment.yaml
  examples/kubernetes/nfs-server/nfs-server.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/L

#53 feat: implement `CreateVolume`
  .github/workflows/sanity.yaml
  Makefile
  deploy/kubernetes/csi-nfs-controller.yaml
  deploy/kubernetes/csi-nfs-node.yaml
  examples/kubernetes/statefulset.yaml
  examples/kubernetes/storageclass-nfs.yaml
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
  pkg/nfs/nfs.go
  pkg/nfs/nodeserver.go
  pkg/nfs/utils.go
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note, size/XL

#68 CI: add GH Actions workflow for Darwin unit tests
  .github/workflows/darwin.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#73 master: update release-tools
  release-tools/build.make
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#71 test: add `ControllerGetCapabilities` and `ValidateVolumeCapabilities in sanity test
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, kind/flake, lgtm, ok-to-test, release-note-none, size/XS
