Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2020-12, with the labels that each got.

#109 CI: enable golint
  .github/workflows/static.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#117 fix: limit node server to deploy only on Linux nodes
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  deploy/csi-nfs-node.yaml
  deploy/example/deployment.yaml
  test/e2e/testsuites/testsuites.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#118 test: refine sanity test script
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/sanity.yaml
  Makefile
  go.mod
  pkg/nfs/nfs.go
  test/sanity/run-test.sh
  vendor/modules.txt
Labels: approved, cncf-cla: yes, release-note-none, size/M

#119 test: upgrade sanity-test to v4.0.2
  test/sanity/run-test.sh
Labels: approved, cncf-cla: yes, release-note-none, size/XS

#120 doc: format yaml files
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
  deploy/example/deployment.yaml
  deploy/example/nfs-provisioner/nginx-pod.yaml
  deploy/example/pvc-nfs-csi-dynamic.yaml
  deploy/example/statefulset.yaml
  deploy/example/storageclass-nfs.yaml
  hack/verify-yamllint.sh
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/M

#122 fix: support mountOptions in CreateVolume
  pkg/mounter/safe_mounter_unix.go
  pkg/nfs/controllerserver.go
  pkg/nfs/fake_mounter.go
  pkg/nfs/nodeserver.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/L
