Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2021-05, with the labels that each got.

#194 add a new helm parameter for livenessProbe health port
  charts/README.md
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/values.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/XS

#196 master: update release-tools
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
  release-tools/pull-test.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#198 chore: upgrade base image to fix CVE issue
  Dockerfile
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/XS

#201 fix: remove unnecessary lock
  pkg/nfs/nodeserver.go
  pkg/nfs/nodeserver_test.go
  pkg/nfs/utils.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/M

#202 chore: upgrade liveness probe and registrar
  charts/README.md
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
Labels: approved, cncf-cla: yes, kind/feature, release-note-none, size/S

#203 master: update release-tools + OWNERS
  OWNERS
  OWNERS_ALIASES
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/OWNERS
  release-tools/OWNERS_ALIASES
  release-tools/build.make
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
  release-tools/verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#197 Remove capacity setting in create Volume response
  pkg/nfs/controllerserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#204 test: run external e2e test using 1.20 suites
  test/external-e2e/run.sh
  test/external-e2e/testdriver.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#205 test: run externel tests with 1.21 suites
  deploy/example/storageclass-nfs.yaml
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
