Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2021-02, with the labels that each got.

#146 fix: add runOnMaster switch for helm chart
  charts/README.md
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#143 cleanup: disable NodeStageVolume
  pkg/nfs/nodeserver.go
Labels: approved, cncf-cla: yes, release-note-none, size/XS

#147 master: update release-tools
  release-tools/README.md
  release-tools/boilerplate/boilerplate.py
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#149 provide more driver info in logs
  Makefile
  go.mod
  pkg/nfs/nfs.go
  pkg/nfs/version.go
  pkg/nfs/version_test.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#151 test: add verify-helm-chart-files.sh script
  charts/index.yaml
  hack/verify-all.sh
  hack/verify-helm-chart-files.sh
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/bug, release-note-none, size/M

#156 fix: makeDir error in CreateVolume
  pkg/nfs/controllerserver.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/XS

#157 set 200Mi limit for csi-provisioner
  Makefile
  charts/README.md
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs/.helmignore
  charts/latest/csi-driver-nfs/Chart.yaml
  charts/latest/csi-driver-nfs/templates/NOTES.txt
  charts/latest/csi-driver-nfs/templates/_helpers.tpl
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-driverinfo.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/templates/rbac-csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  pkg/nfs/utils.go
  pkg/nfs/utils_test.go
Labels: approved, cncf-cla: yes, kind/bug, release-note-none, size/S

#160 feat: add locks for nodeserver publish/unpublish operations
  pkg/nfs/nfs.go
  pkg/nfs/nfs_test.go
  pkg/nfs/nodeserver.go
  pkg/nfs/nodeserver_test.go
  pkg/nfs/utils.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#161 doc: update supported k8s version
  README.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note-none, size/XS

#163 test: add helm chart index verification
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  deploy/csi-nfs-controller.yaml
  hack/verify-helm-chart-files.sh
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S

#164 fix: change base image to debian
  Dockerfile
Labels: approved, cncf-cla: yes, release-note, size/XS

#167 Update release tools
  release-tools/build.make
Labels: approved, cncf-cla: yes, kind/feature, release-note-none, size/XS

#166 feat: add ARCH in Dockerfile
  Dockerfile
Labels: approved, cncf-cla: yes, kind/feature, release-note-none, size/XS

#168 fix: add hostNetwork in controller
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  deploy/csi-nfs-controller.yaml
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/XS
