Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2021-12, with the labels that each got.

#252 fix: v3.0.0 chart
  charts/index.yaml
  charts/v3.0.0/csi-driver-nfs-v3.0.0.tgz
  charts/v3.0.0/csi-driver-nfs/Chart.yaml
  hack/verify-helm-chart.sh
Labels: kind/bug, size/S, cncf-cla: yes, release-note, approved

#253 fix: mount.nfs: Protocol not supported on NFSv3
  Dockerfile
Labels: kind/feature, size/XS, cncf-cla: yes, release-note, approved

#254 fix: driver version print in logging
  cmd/nfsplugin/main.go
  hack/release-image.sh
  pkg/nfs/controllerserver_test.go
  pkg/nfs/nfs.go
  pkg/nfs/nfs_test.go
  test/e2e/e2e_suite_test.go
Labels: kind/bug, size/S, lgtm, cncf-cla: yes, release-note, approved

#255 doc: fix links of docs
  deploy/example/README.md
  deploy/example/nfs-provisioner/README.md
Labels: size/XS, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#256 fix: CVE-2021-43618 in Ubuntu image
  .github/workflows/pluto.yaml
  Dockerfile
  charts/README.md
  charts/latest/csi-driver-nfs-v3.1.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/values.yaml
  cmd/nfsplugin/main.go
  hack/verify-helm-chart-files.sh
  pkg/nfs/controllerserver.go
  pkg/nfs/nodeserver.go
  test/external-e2e/run.sh
Labels: kind/bug, size/M, cncf-cla: yes, release-note, approved

#258 fix: CVE-2021-38561 with golang lib
  go.mod
  go.sum
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: kind/bug, size/M, cncf-cla: yes, release-note, approved

#259 cleanup: remove cpu limits
  charts/README.md
  charts/latest/csi-driver-nfs-v3.1.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
  pkg/nfs/nodeserver.go
Labels: kind/cleanup, size/S, cncf-cla: yes, release-note, approved
