Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2021-01, with the labels that each got.

#127 test: add unit test action on Ubuntu
  .github/workflows/ubuntu.yaml
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/M

#129 test: enable GH actions on all branches
  .github/workflows/darwin.yaml
  .github/workflows/ubuntu.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S

#130 test: add windows unit test action
  .github/workflows/linux.yaml
  .github/workflows/windows.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/S

#124 test: Add missing unit tests for controller server and utils
  pkg/nfs/controllerserver_test.go
  pkg/nfs/utils_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, release-note-none, size/L

#134 Enable spelling and boilerplate checks in prow and local tests
  .prow.sh
  docs/csi-dev.md
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/S

#136 test: refactor verify example test
  Makefile
  deploy/example/deployment.yaml
  hack/verify-examples.sh
  test/e2e/e2e_suite_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/M

#137 chore: use klog instead of glog
  cmd/nfsplugin/main.go
  go.mod
  pkg/nfs/controllerserver.go
  pkg/nfs/indentityserver.go
  pkg/nfs/nfs.go
  pkg/nfs/nodeserver.go
  pkg/nfs/server.go
  pkg/nfs/utils.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/inconshreveable/mousetrap/README.md
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.mailmap
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/CONTRIBUTING.md
  vendor/github.com/spf13/cobra/LICENSE.txt
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/custom_completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, release-note, size/XXL

#138 fix: reduce driver logs
  .github/workflows/darwin.yaml
  .github/workflows/linux.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
  hack/verify-examples.sh
  pkg/nfs/indentityserver.go
  pkg/nfs/utils.go
  pkg/nfs/utils_test.go
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/M

#139 chore: rename indentityserver.go to identityserver.go
  pkg/nfs/identityserver.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, release-note-none, size/XS

#140 chore: update latest chart
  charts/latest/csi-driver-nfs-latest.tgz
Labels: approved, cncf-cla: yes, kind/cleanup, release-note-none, size/XS

#141 master: update release-tools
  release-tools/prow.sh
  release-tools/verify-boilerplate.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#144 fix: add latest helm chart file
  charts/index.yaml
  charts/latest/csi-driver-nfs-latest.tgz
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs/Chart.yaml
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/bug, release-note, size/S

#145 fix: update tgz chart file
  charts/v2.0.0/csi-driver-nfs-v2.0.0.tgz
  hack/verify-helm-chart.sh
Labels: approved, cncf-cla: yes, kind/bug, release-note-none, size/S
