Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2021-11, with the labels that each got.

#240 fix: armv7 docker builds
  Dockerfile
  Makefile
Labels: kind/bug, size/XS, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#243 feat: add sidecar container cpu,memory limits
  charts/README.md
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
Labels: kind/feature, size/M, cncf-cla: yes, release-note, approved

#244 Windows go version
  .github/workflows/darwin.yaml
  .github/workflows/linux.yaml
  .github/workflows/windows.yaml
Labels: kind/failing-test, size/S, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#245 master: update release-tools
  release-tools/go-get-kubernetes.sh
  release-tools/prow.sh
Labels: size/M, lgtm, release-note-none, cncf-cla: yes, approved

#247 feat: increase sidecar container cpu limits
  charts/README.md
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
Labels: kind/feature, size/L, cncf-cla: yes, release-note, approved

#230 fix: vulnerability issue in docker image
  .github/workflows/trivy.yaml
  Dockerfile
  Makefile
Labels: kind/bug, size/M, cncf-cla: yes, release-note, approved

#248 doc: update README
  README.md
Labels: size/S, release-note-none, kind/documentation, cncf-cla: yes, approved

#249 doc: cut v3.0.0 release
  README.md
  charts/index.yaml
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/v3.0.0/csi-driver-nfs-v3.0.0.tgz
  charts/v3.0.0/csi-driver-nfs/.helmignore
  charts/v3.0.0/csi-driver-nfs/Chart.yaml
  charts/v3.0.0/csi-driver-nfs/templates/NOTES.txt
  charts/v3.0.0/csi-driver-nfs/templates/_helpers.tpl
  charts/v3.0.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v3.0.0/csi-driver-nfs/templates/csi-nfs-driverinfo.yaml
  charts/v3.0.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/v3.0.0/csi-driver-nfs/templates/rbac-csi-nfs-controller.yaml
  charts/v3.0.0/csi-driver-nfs/values.yaml
  deploy/v3.0.0/csi-nfs-controller.yaml
  deploy/v3.0.0/csi-nfs-driverinfo.yaml
  deploy/v3.0.0/csi-nfs-node.yaml
  deploy/v3.0.0/rbac-csi-nfs-controller.yaml
  docs/install-csi-driver-master.md
  docs/install-csi-driver-v3.0.0.md
  docs/install-nfs-csi-driver.md
Labels: size/XL, lgtm, kind/documentation, cncf-cla: yes, release-note, approved

#250 chore: switch master branch to use v3.1.0
  Makefile
  charts/index.yaml
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs-v3.1.0.tgz
  charts/latest/csi-driver-nfs/Chart.yaml
Labels: size/S, release-note-none, kind/documentation, cncf-cla: yes, approved
