Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2021-07, with the labels that each got.

#214 doc: add daemonset-nfs-ephemeral.yaml example
  deploy/example/daemonset-nfs-ephemeral.yaml
  hack/verify-examples.sh
  test/external-e2e/run.sh
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/M

#215 master: update release-tools
  release-tools/KUBERNETES_CSI_OWNERS_ALIASES
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#216 feat: support alternative driver name
  charts/README.md
  charts/latest/csi-driver-nfs-v3.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-driverinfo.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/templates/rbac-csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/values.yaml
  cmd/nfsplugin/main.go
  deploy/csi-nfs-controller.yaml
  hack/verify-examples.sh
  pkg/nfs/controllerserver_test.go
  pkg/nfs/nfs.go
  pkg/nfs/nfs_test.go
  pkg/nfs/version.go
  pkg/nfs/version_test.go
  test/e2e/driver/nfs_driver.go
  test/e2e/e2e_suite_test.go
  test/external-e2e/run.sh
  test/utils/nfs_log.sh
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/L
