Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2022-03, with the labels that each got.

#292 feat: add mountPermissions parameter in storage class
  docs/driver-parameters.md
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
  pkg/nfs/nfs.go
  pkg/nfs/nodeserver.go
  pkg/nfs/nodeserver_test.go
  test/e2e/e2e_suite_test.go
Labels: kind/feature, size/L, cncf-cla: yes, release-note, approved

#294 fix: CVE-2022-0778 in image build
  Dockerfile
Labels: kind/bug, size/XS, release-note-none, cncf-cla: yes, approved

#295 doc: add nconnect mount option in nfs example
  deploy/example/pv-nfs-csi.yaml
  deploy/example/storageclass-nfs.yaml
  test/e2e/dynamic_provisioning_test.go
Labels: size/XS, release-note-none, kind/documentation, cncf-cla: yes, approved

#297 chore: fix pushing image pipeline broken
  Dockerfile
Labels: kind/failing-test, size/XS, release-note-none, cncf-cla: yes, approved

#298 fix: post-csi-driver-nfs-push-images failure
  Dockerfile
Labels: kind/failing-test, size/XS, release-note-none, cncf-cla: yes, approved

#299 fix: leader-election namespace issue
  charts/latest/csi-driver-nfs-v3.2.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
Labels: kind/bug, size/XS, lgtm, cncf-cla: yes, release-note, approved

#301 Address CVE-2022-21698
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: kind/bug, lgtm, size/L, cncf-cla: yes, release-note, approved, ok-to-test

#302 fix: CVE issues in image build
  Dockerfile
Labels: kind/bug, size/XS, cncf-cla: yes, release-note, approved

#303 fix: CVE issues in image build on release-3.1
  Dockerfile
Labels: kind/bug, size/S, cncf-cla: yes, release-note, approved

#304 fix: CVE issues in image build on release-3.0
  Dockerfile
Labels: kind/bug, size/S, cncf-cla: yes, release-note, approved
