Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2022-04, with the labels that each got.

#305 fix: CVE-2018-25032 in image build
  .github/workflows/codeql-analysis.yml
  Dockerfile
Labels: kind/bug, size/M, cncf-cla: yes, release-note, approved

#306 doc: refine PV doc
  deploy/example/README.md
  deploy/example/pv-nfs-csi.yaml
  deploy/example/pvc-nfs-csi-static.yaml
  deploy/example/storageclass-nfs.yaml
Labels: size/S, release-note-none, kind/documentation, cncf-cla: yes, approved

#308 test: fix golint error
  hack/verify-all.sh
Labels: kind/failing-test, size/XS, release-note-none, cncf-cla: yes, approved

#307 master: update release-tools
  release-tools/prow.sh
  release-tools/verify-spelling.sh
Labels: size/XS, lgtm, release-note-none, cncf-cla: yes, approved

#309 test: fix golinter error
  .github/workflows/static.yaml
Labels: kind/failing-test, size/XS, lgtm, release-note-none, cncf-cla: yes, approved

#310 fix: disallow block volume capability
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
  pkg/nfs/nfs.go
  pkg/nfs/nfs_test.go
  test/external-e2e/run.sh
  test/external-e2e/testdriver.yaml
Labels: kind/failing-test, size/L, cncf-cla: yes, release-note, approved

#311 chore: change MCR repo to gcr repo
  charts/README.md
  charts/latest/csi-driver-nfs-v3.2.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  charts/v3.0.0/csi-driver-nfs-v3.0.0.tgz
  charts/v3.0.0/csi-driver-nfs/values.yaml
  charts/v3.1.0/csi-driver-nfs-v3.1.0.tgz
  charts/v3.1.0/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
  deploy/v3.0.0/csi-nfs-controller.yaml
  deploy/v3.0.0/csi-nfs-node.yaml
  deploy/v3.1.0/csi-nfs-controller.yaml
  deploy/v3.1.0/csi-nfs-node.yaml
Labels: kind/cleanup, size/S, release-note-none, cncf-cla: yes, approved

#313 chore: Update golang.org/x/crypto for CVE-2022-27191
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64.go
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/ed25519/ed25519_go113.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/const.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/edwards25519.go
  vendor/golang.org/x/crypto/internal/poly1305/bits_compat.go
  vendor/golang.org/x/crypto/internal/poly1305/bits_go1.13.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/poly1305.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.s
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/doc.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: size/XXL, kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved

#315 doc: align the endpoint with environment variable used below to avoid confusing
  docs/csi-dev.md
Labels: size/XS, lgtm, release-note-none, kind/documentation, cncf-cla: yes, approved, ok-to-test

#316 fix: CVE-2022-1271 in image build
  Dockerfile
Labels: kind/bug, size/XS, lgtm, cncf-cla: yes, release-note, approved

#319 fix: NodeUnpublishVolume should be idempotent
  pkg/nfs/nodeserver.go
  pkg/nfs/nodeserver_test.go
Labels: kind/bug, size/XS, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#320 fix: use mount.CleanupMountPoint in NodeUnpublishVolume for handling stale nfs connections during unmount process
  pkg/nfs/nodeserver.go
  pkg/nfs/nodeserver_test.go
Labels: kind/bug, size/S, cncf-cla: yes, release-note, approved

#322 nfs: update livenessprobe and node driver registrar to latest
  charts/README.md
  charts/latest/csi-driver-nfs-v3.2.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
Labels: size/S, lgtm, release-note-none, cncf-cla: yes, approved

#323 chore: switch master branch to use v4.0.0
  Makefile
  charts/index.yaml
  charts/latest/csi-driver-nfs-v3.2.0.tgz
  charts/latest/csi-driver-nfs-v4.0.0.tgz
  charts/latest/csi-driver-nfs/Chart.yaml
Labels: size/S, release-note-none, cncf-cla: yes, approved
