Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2022-01, with the labels that each got.

#262 feat: support mountOptions in DeleteVolume
  Makefile
  charts/latest/csi-driver-nfs-v3.1.0.tgz
  charts/latest/csi-driver-nfs/templates/rbac-csi-nfs-controller.yaml
  deploy/rbac-csi-nfs-controller.yaml
  docs/driver-parameters.md
  pkg/nfs/controllerserver.go
  pkg/nfs/nfs.go
  pkg/nfs/utils.go
  pkg/nfs/utils_test.go
  test/e2e/e2e_suite_test.go
Labels: kind/feature, size/M, cncf-cla: yes, release-note, approved

#264 doc: update mountOptions for DeleteVolume doc
  deploy/example/storageclass-nfs.yaml
  docs/driver-parameters.md
Labels: size/M, release-note-none, kind/documentation, cncf-cla: yes, approved

#263 feat: add workingMountDir in chart config
  .github/workflows/linux.yaml
  charts/README.md
  charts/latest/csi-driver-nfs-v3.1.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/values.yaml
  cmd/nfsplugin/main.go
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
  pkg/nfs/nfs.go
  pkg/nfs/nfs_test.go
  pkg/nfs/nodeserver.go
  pkg/nfs/nodeserver_test.go
  test/e2e/e2e_suite_test.go
Labels: kind/feature, size/L, cncf-cla: yes, release-note, approved

#265 feat: change volume id format
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
Labels: kind/feature, size/L, cncf-cla: yes, release-note, approved

#267 fix: ValidateVolumeCapabilities
  .github/workflows/static.yaml
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
Labels: kind/bug, size/M, cncf-cla: yes, release-note, approved

#269 doc: cut v3.1.0 release
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/csi-driver-nfs-v3.1.0.tgz
  charts/v3.1.0/csi-driver-nfs-v3.1.0.tgz
  charts/v3.1.0/csi-driver-nfs/.helmignore
  charts/v3.1.0/csi-driver-nfs/Chart.yaml
  charts/v3.1.0/csi-driver-nfs/templates/NOTES.txt
  charts/v3.1.0/csi-driver-nfs/templates/_helpers.tpl
  charts/v3.1.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v3.1.0/csi-driver-nfs/templates/csi-nfs-driverinfo.yaml
  charts/v3.1.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/v3.1.0/csi-driver-nfs/templates/rbac-csi-nfs-controller.yaml
  charts/v3.1.0/csi-driver-nfs/values.yaml
  deploy/v3.1.0/csi-nfs-controller.yaml
  deploy/v3.1.0/csi-nfs-driverinfo.yaml
  deploy/v3.1.0/csi-nfs-node.yaml
  deploy/v3.1.0/rbac-csi-nfs-controller.yaml
  docs/install-csi-driver-v3.1.0.md
  docs/install-nfs-csi-driver.md
Labels: size/XL, cncf-cla: yes, release-note, approved

#270 chore: switch master branch to use v3.2.0
  Makefile
  charts/index.yaml
  charts/latest/csi-driver-nfs-v3.1.0.tgz
  charts/latest/csi-driver-nfs-v3.2.0.tgz
  charts/latest/csi-driver-nfs/Chart.yaml
Labels: size/S, release-note-none, kind/documentation, cncf-cla: yes, approved

#271 feat: upgrade to csi-provisioner v3.1.0
  .github/workflows/static.yaml
  README.md
  charts/README.md
  charts/latest/csi-driver-nfs-v3.2.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-driverinfo.yaml
  test/external-e2e/run.sh
Labels: size/S, release-note-none, cncf-cla: yes, approved

#272 update base image version of plugin binary to fix CVEs
  Dockerfile
Labels: size/XS, lgtm, release-note-none, cncf-cla: yes, approved

#273 cleanup: remove unnecessary CVE packages
  Dockerfile
Labels: size/XS, kind/cleanup, release-note-none, cncf-cla: yes, approved

#276 doc: comment mount-options in example
  deploy/example/storageclass-nfs.yaml
Labels: size/XS, release-note-none, cncf-cla: yes, approved

#281 chore: set replica of controller as 1 by default
  charts/README.md
  charts/latest/csi-driver-nfs-v3.2.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
Labels: kind/feature, size/XS, cncf-cla: yes, release-note, approved

#279 feat: add kubeletDir in chart config
  charts/README.md
  charts/latest/csi-driver-nfs-v3.2.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/values.yaml
Labels: kind/feature, size/S, lgtm, cncf-cla: yes, release-note, approved, ok-to-test
