Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2023-10, with the labels that each got.

#512 fix: increase snapshot timeout as 20min
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v4.4.0/csi-driver-nfs-v4.4.0.tgz
  charts/v4.4.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  deploy/csi-nfs-controller.yaml
  deploy/v4.4.0/csi-nfs-controller.yaml
Labels: kind/bug, size/XS, lgtm, cncf-cla: yes, release-note, approved

#516 fix: flag panic if a flag is defined after being set
  cmd/nfsplugin/main.go
Labels: kind/bug, size/XS, cncf-cla: yes, release-note, approved

#521 feat: propagate default host configuration files to csi node
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/values.yaml
Labels: size/S, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#527 Bump Go and golang.org/x/... to recent versions
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/deviceauth.go
  vendor/golang.org/x/oauth2/internal/token.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/golang.org/x/time/AUTHORS
  vendor/golang.org/x/time/CONTRIBUTORS
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/sometimes.go
  vendor/golang.org/x/tools/internal/typeparams/coretype.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/modules.txt
Labels: kind/bug, size/XL, lgtm, release-note-none, cncf-cla: yes, approved

#528 go.mod: Fix unresolvable indirect dependency
  go.mod
  vendor/modules.txt
Labels: size/XS, lgtm, release-note-none, cncf-cla: yes, approved
