Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2023-11, with the labels that each got.

#537 doc: fix doc typo
  charts/README.md
Labels: size/XS, release-note-none, kind/documentation, cncf-cla: yes, approved

#536 test: add more gomod check
  hack/verify-gomod.sh
Labels: size/XS, release-note-none, cncf-cla: yes, approved

#539 feat: upgrade sidecar image versions
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/M, cncf-cla: yes, release-note, approved

#538 feat: switch to bookworm debian base image
  Dockerfile
Labels: kind/feature, size/XS, cncf-cla: yes, release-note, approved

#530 feat: archive on delete support
  charts/README.md
  docs/driver-parameters.md
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
  pkg/nfs/utils.go
  pkg/nfs/utils_test.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/e2e_suite_test.go
Labels: kind/feature, lgtm, size/L, cncf-cla: yes, release-note, approved, ok-to-test

#543 doc: cut v4.5.0 release
  Makefile
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/v4.5.0/csi-driver-nfs-v4.5.0.tgz
  charts/v4.5.0/csi-driver-nfs/.helmignore
  charts/v4.5.0/csi-driver-nfs/Chart.yaml
  charts/v4.5.0/csi-driver-nfs/templates/NOTES.txt
  charts/v4.5.0/csi-driver-nfs/templates/_helpers.tpl
  charts/v4.5.0/csi-driver-nfs/templates/crd-csi-snapshot.yaml
  charts/v4.5.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v4.5.0/csi-driver-nfs/templates/csi-nfs-driverinfo.yaml
  charts/v4.5.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/v4.5.0/csi-driver-nfs/templates/csi-snapshot-controller.yaml
  charts/v4.5.0/csi-driver-nfs/templates/rbac-csi-nfs.yaml
  charts/v4.5.0/csi-driver-nfs/templates/rbac-snapshot-controller.yaml
  charts/v4.5.0/csi-driver-nfs/values.yaml
  deploy/v4.5.0/crd-csi-snapshot.yaml
  deploy/v4.5.0/csi-nfs-controller.yaml
  deploy/v4.5.0/csi-nfs-driverinfo.yaml
  deploy/v4.5.0/csi-nfs-node.yaml
  deploy/v4.5.0/csi-snapshot-controller.yaml
  deploy/v4.5.0/rbac-csi-nfs.yaml
  deploy/v4.5.0/rbac-snapshot-controller.yaml
  docs/install-csi-driver-v4.5.0.md
  docs/install-nfs-csi-driver.md
Labels: size/XXL, cncf-cla: yes, release-note, approved

#500 fixed broken links of testgrid dashboard
  README.md
Labels: size/XS, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#551 test: upgrade golangci/golangci-lint-action to v1.54
  .github/workflows/static.yaml
  .golangci.yml
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
  pkg/nfs/fake_mounter.go
  pkg/nfs/identityserver.go
  pkg/nfs/nodeserver.go
  pkg/nfs/utils.go
  test/e2e/driver/nfs_driver.go
  test/e2e/testsuites/dynamically_provisioned_inline_volume.go
  test/e2e/testsuites/specs.go
Labels: size/M, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#552 fix: CVE-2023-5528
  go.mod
  go.sum
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/parse.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/context.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/convert.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/errors.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/fieldmask.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/handler.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/marshal_jsonpb.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/mux.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/query.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/utilities/string_array_flag.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/k8s.io/mount-utils/fake_mounter.go
  vendor/k8s.io/mount-utils/mount.go
  vendor/k8s.io/mount-utils/mount_helper_common.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_unsupported.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/k8s.io/mount-utils/resizefs_linux.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, cncf-cla: yes, release-note, approved

#542 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, release-note-none, cncf-cla: yes, approved

#554 doc: fix readOnly setting doc
  deploy/example/deployment.yaml
  deploy/example/nfs-provisioner/nginx-pod.yaml
  deploy/example/nginx-pod-inline-volume.yaml
  deploy/example/pv-nfs-csi.yaml
  deploy/example/statefulset.yaml
Labels: size/XS, release-note-none, kind/documentation, cncf-cla: yes, approved

#553 [chore] Update release tools2
  release-tools/SIDECAR_RELEASE_PROCESS.md
  release-tools/generate_patch_release_notes.sh
  release-tools/prow.sh
  release-tools/pull-test.sh
Labels: kind/cleanup, size/L, release-note-none, cncf-cla: yes, approved

#555 doc: add volume cloning doc
  README.md
  deploy/example/cloning/README.md
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/cloning/pvc-nfs-cloning.yaml
  deploy/example/nginx-pod-nfs.yaml
  hack/verify-yamllint.sh
Labels: lgtm, size/L, release-note-none, kind/documentation, cncf-cla: yes, approved, ok-to-test
