Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2023-04, with the labels that each got.

#435 fix: CVE-2022-3294
  go.mod
  go.sum
  vendor/k8s.io/api/apps/v1/generated.proto
  vendor/k8s.io/api/apps/v1/types.go
  vendor/k8s.io/api/apps/v1beta1/generated.proto
  vendor/k8s.io/api/apps/v1beta1/types.go
  vendor/k8s.io/api/apps/v1beta2/generated.proto
  vendor/k8s.io/api/apps/v1beta2/types.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/apiserver/pkg/audit/union.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/client-go/tools/clientcmd/auth_loaders.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/transport/config.go
  vendor/k8s.io/client-go/transport/transport.go
  vendor/k8s.io/component-base/version/.gitattributes
  vendor/k8s.io/kubernetes/pkg/api/v1/pod/util.go
  vendor/k8s.io/kubernetes/pkg/apis/apps/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/events.go
  vendor/k8s.io/kubernetes/pkg/controller/controller_utils.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/proxy/util/utils.go
  vendor/k8s.io/kubernetes/pkg/volume/util/subpath/subpath_linux.go
  vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
  vendor/k8s.io/kubernetes/test/e2e/framework/nodes_util.go
  vendor/k8s.io/kubernetes/test/e2e/framework/test_context.go
  vendor/k8s.io/kubernetes/test/e2e/framework/util.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/conn.go
Labels: kind/bug, size/XL, cncf-cla: yes, release-note, approved

#430 feat: implement snapshots as tarballs
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-snapshot-controller.yaml
  charts/latest/csi-driver-nfs/templates/rbac-csi-nfs.yaml
  charts/latest/csi-driver-nfs/templates/rbac-snapshot-controller.yaml
  charts/latest/csi-driver-nfs/templates/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  charts/latest/csi-driver-nfs/templates/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  charts/latest/csi-driver-nfs/templates/snapshot.storage.k8s.io_volumesnapshots.yaml
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/example/snapshot-nfs-dynamic.yaml
  deploy/example/snapshotclass-nfs.yaml
  deploy/install-driver.sh
  deploy/rbac-csi-nfs.yaml
  deploy/rbac-snapshot-controller.yaml
  deploy/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  deploy/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  deploy/snapshot.storage.k8s.io_volumesnapshots.yaml
  deploy/uninstall-driver.sh
  go.mod
  hack/verify-helm-chart.sh
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
  pkg/nfs/nfs.go
  test/external-e2e/run.sh
  test/external-e2e/testdriver.yaml
Labels: kind/feature, size/XXL, lgtm, cncf-cla: yes, release-note, approved

#437 feat: enable securityContext.seccompProfile, set system-cluster-critical
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/templates/csi-snapshot-controller.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, cncf-cla: yes, release-note, approved

#438 test(e2e): change the storageclass configuration method in the test file
  deploy/example/statefulset.yaml
Labels: size/XS, kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#440 fix: set ClusterFirstWithHostNet as default dnsPolicy
  Makefile
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
Labels: kind/bug, size/S, cncf-cla: yes, release-note, approved

#441 chore: upgrade csi sidecar container images
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
Labels: kind/feature, size/S, lgtm, release-note-none, cncf-cla: yes, approved
