Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2024-12, with the labels that each got.

#807 fix: driver name in storage class helm configure
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/storageclass.yaml
  charts/v4.9.0/csi-driver-nfs-v4.9.0.tgz
  charts/v4.9.0/csi-driver-nfs/templates/storageclass.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, release-note, approved

#811 feat: add volume resize support
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/rbac-csi-nfs.yaml
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/rbac-csi-nfs.yaml
  hack/verify-helm-chart.sh
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
  pkg/nfs/nfs.go
  test/e2e/dynamic_provisioning_test.go
  test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
  test/external-e2e/testdriver.yaml
Labels: kind/feature, size/L, cncf-cla: yes, release-note, approved

#812 Prow update master
  release-tools/build.make
  release-tools/prow.sh
  release-tools/pull-test.sh
Labels: size/M, kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#816 fix: runOnControlPlane chart config
  Makefile
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v4.9.0/csi-driver-nfs-v4.9.0.tgz
  charts/v4.9.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
Labels: kind/bug, size/M, cncf-cla: yes, release-note, approved

#815 fix: CVE-2024-45337
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/modules.txt
Labels: kind/bug, size/S, cncf-cla: yes, release-note, approved

#818 feat: upgrade to snapshot v8.2.0
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/rbac-snapshot-controller.yaml
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/rbac-snapshot-controller.yaml
Labels: kind/feature, size/S, cncf-cla: yes, release-note, approved

#821 chore: upgrade k8s.io/mount-utils to v1.32.0
  go.mod
  go.sum
  vendor/github.com/moby/sys/mountinfo/mounted_linux.go
  vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go
  vendor/github.com/moby/sys/userns/LICENSE
  vendor/github.com/moby/sys/userns/userns.go
  vendor/github.com/moby/sys/userns/userns_linux.go
  vendor/github.com/moby/sys/userns/userns_linux_fuzzer.go
  vendor/github.com/moby/sys/userns/userns_unsupported.go
  vendor/k8s.io/mount-utils/mount_linux.go
  vendor/k8s.io/mount-utils/mount_windows.go
  vendor/k8s.io/utils/integer/integer.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/k8s.io/utils/net/multi_listen.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: kind/feature, size/XL, release-note-none, cncf-cla: yes, approved

#822 test: upgrade csi-test to v5.3.1
  test/sanity/run-test.sh
Labels: size/XS, kind/cleanup, release-note-none, cncf-cla: yes, approved

#820 feat: add controller.enableSnapshotter chart config
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/values.yaml
Labels: kind/feature, size/XS, cncf-cla: yes, release-note, approved

#823 feat: support runOnControlPlane on csi-snapshot-controller
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, cncf-cla: yes, release-note, approved

#826 feat: added volumesnapshotclass to helm chart
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/snapshotclass.yaml
  charts/latest/csi-driver-nfs/values.yaml
  deploy/snapshotclass.yaml
Labels: size/S, lgtm, cncf-cla: yes, release-note, approved, ok-to-test

#832 chore: Update csi release tools
  release-tools/cloudbuild.yaml
  release-tools/prow.sh
Labels: size/XS, kind/cleanup, release-note-none, cncf-cla: yes, approved
