Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2024-07, with the labels that each got.

#700 test: fix trivy action failure
  .github/workflows/trivy.yaml
Labels: size/XS, release-note-none, cncf-cla: yes, approved

#701 fix: storage class mountOptions indent
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/storageclass.yaml
  charts/v4.7.0/csi-driver-nfs-v4.7.0.tgz
  charts/v4.7.0/csi-driver-nfs/templates/storageclass.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, release-note, approved

#697 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/values.yaml
  charts/v4.7.0/csi-driver-nfs-v4.7.0.tgz
  charts/v4.7.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v4.7.0/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
  deploy/csi-snapshot-controller.yaml
  deploy/v4.7.0/csi-nfs-controller.yaml
  deploy/v4.7.0/csi-nfs-node.yaml
  deploy/v4.7.0/csi-snapshot-controller.yaml
Labels: size/M, release-note-none, cncf-cla: yes, approved

#708 Fix org name in links to snapshot resources
  deploy/example/snapshot/README.md
Labels: size/XS, lgtm, release-note-none, kind/documentation, cncf-cla: yes, approved, ok-to-test

#710 doc: cut v4.8.0 release
  Makefile
  README.md
  charts/README.md
  charts/index.yaml
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/v4.8.0/csi-driver-nfs-v4.8.0.tgz
  charts/v4.8.0/csi-driver-nfs/.helmignore
  charts/v4.8.0/csi-driver-nfs/Chart.yaml
  charts/v4.8.0/csi-driver-nfs/templates/NOTES.txt
  charts/v4.8.0/csi-driver-nfs/templates/_helpers.tpl
  charts/v4.8.0/csi-driver-nfs/templates/crd-csi-snapshot.yaml
  charts/v4.8.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v4.8.0/csi-driver-nfs/templates/csi-nfs-driverinfo.yaml
  charts/v4.8.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/v4.8.0/csi-driver-nfs/templates/csi-snapshot-controller.yaml
  charts/v4.8.0/csi-driver-nfs/templates/rbac-csi-nfs.yaml
  charts/v4.8.0/csi-driver-nfs/templates/rbac-snapshot-controller.yaml
  charts/v4.8.0/csi-driver-nfs/templates/storageclass.yaml
  charts/v4.8.0/csi-driver-nfs/values.yaml
  deploy/v4.8.0/crd-csi-snapshot.yaml
  deploy/v4.8.0/csi-nfs-controller.yaml
  deploy/v4.8.0/csi-nfs-driverinfo.yaml
  deploy/v4.8.0/csi-nfs-node.yaml
  deploy/v4.8.0/csi-snapshot-controller.yaml
  deploy/v4.8.0/rbac-csi-nfs.yaml
  deploy/v4.8.0/rbac-snapshot-controller.yaml
  deploy/v4.8.0/storageclass.yaml
  docs/install-csi-driver-v4.8.0.md
  docs/install-nfs-csi-driver.md
Labels: size/XXL, release-note-none, kind/documentation, cncf-cla: yes, approved

#718 fix: unmount detection failure
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
Labels: kind/bug, size/S, release-note-none, cncf-cla: yes, approved

#719 fix: unmount detection failure
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
Labels: kind/bug, size/XS, release-note-none, cncf-cla: yes, approved

#720 fix: tmp path mount permission error on charts
  charts/v4.3.0/csi-driver-nfs-v4.3.0.tgz
  charts/v4.3.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/v4.4.0/csi-driver-nfs-v4.4.0.tgz
  charts/v4.4.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/v4.5.0/csi-driver-nfs-v4.5.0.tgz
  charts/v4.5.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/v4.6.0/csi-driver-nfs-v4.6.0.tgz
  charts/v4.6.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/v4.7.0/csi-driver-nfs-v4.7.0.tgz
  charts/v4.7.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/v4.8.0/csi-driver-nfs-v4.8.0.tgz
  charts/v4.8.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v4.8.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
Labels: kind/bug, size/S, cncf-cla: yes, release-note, approved

#725 fix: add pv patch permission with HonorPVReclaimPolicy enabled
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/rbac-csi-nfs.yaml
  charts/v4.7.0/csi-driver-nfs-v4.7.0.tgz
  charts/v4.7.0/csi-driver-nfs/templates/rbac-csi-nfs.yaml
  charts/v4.8.0/csi-driver-nfs-v4.8.0.tgz
  charts/v4.8.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v4.8.0/csi-driver-nfs/templates/rbac-csi-nfs.yaml
  deploy/csi-nfs-controller.yaml
  deploy/rbac-csi-nfs.yaml
  deploy/v4.7.0/rbac-csi-nfs.yaml
  deploy/v4.8.0/csi-nfs-controller.yaml
  deploy/v4.8.0/rbac-csi-nfs.yaml
Labels: kind/bug, size/S, cncf-cla: yes, release-note, approved
