Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2024-11, with the labels that each got.

#792 fix: add timeout on mount to fix stuck issue
  pkg/nfs/nodeserver.go
  pkg/nfs/utils.go
  pkg/nfs/utils_test.go
Labels: kind/bug, size/M, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#796 chore: update CSI spec to v1.10.0
  go.mod
  go.sum
  pkg/nfs/controllerserver.go
  pkg/nfs/identityserver.go
  pkg/nfs/identityserver_test.go
  pkg/nfs/nfs_test.go
  pkg/nfs/nodeserver.go
  pkg/nfs/nodeserver_test.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
  vendor/github.com/container-storage-interface/spec/lib/go/csi/csi_grpc.pb.go
  vendor/github.com/golang/protobuf/ptypes/wrappers/wrappers.pb.go
  vendor/modules.txt
Labels: kind/feature, size/XXL, release-note-none, cncf-cla: yes, approved

#797 chore: update dependabot
  .github/dependabot.yaml
Labels: kind/cleanup, size/S, release-note-none, cncf-cla: yes, approved

#800 doc: missing keyword pod in command
  docs/csi-debug.md
Labels: size/XS, lgtm, release-note-none, kind/documentation, cncf-cla: yes, approved, ok-to-test

#804 cleanup: remove unused livenessProbe in registrar container
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  deploy/csi-nfs-node.yaml
Labels: kind/cleanup, size/S, release-note-none, cncf-cla: yes, approved
