Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2024-09, with the labels that each got.

#754 fix: delete volume error in archive deletion mode
  pkg/nfs/controllerserver.go
  pkg/nfs/nfs.go
Labels: kind/bug, size/S, cncf-cla: yes, release-note, approved

#759 …Update README.md to note external-snapshotter is required
  deploy/example/snapshot/README.md
Labels: size/XS, lgtm, release-note-none, kind/documentation, cncf-cla: yes, approved, ok-to-test

#761 chore: upgrade to debian-base:bookworm-v1.0.4 base image
  Dockerfile
Labels: kind/feature, size/XS, release-note-none, cncf-cla: yes, approved

#765 chore: upgrade golint version
  .github/workflows/static.yaml
  pkg/nfs/controllerserver.go
  pkg/nfs/nfs.go
  pkg/nfs/nfs_test.go
  pkg/nfs/nodeserver.go
  pkg/nfs/nodeserver_test.go
  pkg/nfs/server.go
  test/e2e/dynamic_provisioning_test.go
  test/utils/testutil/testutil.go
Labels: size/M, kind/cleanup, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test

#766 chore: upgrade golang version
  .github/workflows/trivy.yaml
  go.mod
Labels: kind/failing-test, size/XS, release-note-none, cncf-cla: yes, approved

#769 chore: upgrade sidecar image versions
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, release-note-none, cncf-cla: yes, approved

#770 fix: remove parent dir in DeleteVolume
  pkg/nfs/controllerserver.go
  pkg/nfs/utils.go
  pkg/nfs/utils_test.go
  test/e2e/e2e_suite_test.go
Labels: kind/bug, size/M, cncf-cla: yes, release-note, approved
