Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2024-03, with the labels that each got.

#628 fix: snapshot sidecar rbac permission issue
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/rbac-csi-nfs.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, release-note, approved

#629 fix: snapshot sidecar rbac permission issue on v4.5.0, v4.6.0 charts
  charts/v4.5.0/csi-driver-nfs-v4.5.0.tgz
  charts/v4.5.0/csi-driver-nfs/templates/rbac-csi-nfs.yaml
  charts/v4.6.0/csi-driver-nfs-v4.6.0.tgz
  charts/v4.6.0/csi-driver-nfs/templates/rbac-csi-nfs.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, release-note, approved

#637 feat: add baseRepo field in helm charts
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/templates/csi-snapshot-controller.yaml
  charts/latest/csi-driver-nfs/values.yaml
  charts/v4.6.0/csi-driver-nfs-v4.6.0.tgz
  charts/v4.6.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v4.6.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/v4.6.0/csi-driver-nfs/templates/csi-snapshot-controller.yaml
  charts/v4.6.0/csi-driver-nfs/values.yaml
Labels: size/M, cncf-cla: yes, release-note, approved

#639 feat: use new restricted liveness probe endpoint
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/values.yaml
Labels: kind/feature, size/S, lgtm, cncf-cla: yes, release-note, approved, ok-to-test
