Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2024-04, with the labels that each got.

#641 feat: use new restricted liveness probe endpoint on v4.6.0
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-nfs-node.yaml
  charts/latest/csi-driver-nfs/values.yaml
  charts/v4.6.0/csi-driver-nfs-v4.6.0.tgz
  charts/v4.6.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v4.6.0/csi-driver-nfs/templates/csi-nfs-node.yaml
  deploy/csi-nfs-controller.yaml
  deploy/csi-nfs-node.yaml
  deploy/v4.6.0/csi-nfs-controller.yaml
  deploy/v4.6.0/csi-nfs-node.yaml
Labels: kind/feature, size/M, cncf-cla: yes, release-note, approved

#645 feat: add StorageClass definition in Helm charts
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/storageclass.yaml
  charts/latest/csi-driver-nfs/values.yaml
  deploy/storageclass.yaml
Labels: kind/feature, size/M, lgtm, cncf-cla: yes, release-note, approved, ok-to-test

#655 fix: CVE-2024-3177
  .trivyignore
  go.mod
  go.sum
  vendor/github.com/onsi/gomega/CHANGELOG.md
  vendor/github.com/onsi/gomega/gomega_dsl.go
  vendor/github.com/onsi/gomega/matchers.go
  vendor/github.com/onsi/gomega/matchers/receive_matcher.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/cel/composition.go
  vendor/k8s.io/apiserver/pkg/endpoints/discovery/aggregated/handler.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/server/config.go
  vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go
  vendor/k8s.io/apiserver/pkg/server/options/recommended.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/lister_watcher.go
  vendor/k8s.io/apiserver/pkg/storage/cacher/watch_progress.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/interface.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go
  vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics/metrics.go
  vendor/k8s.io/component-base/metrics/prometheus/slis/metrics.go
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/volume/util/types/types.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: kind/bug, size/XXL, cncf-cla: yes, release-note, approved
