Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2024-08, with the labels that each got.

#728 Update README.md
  deploy/example/nfs-provisioner/README.md
Labels: size/S, lgtm, release-note-none, kind/documentation, cncf-cla: yes, approved, ok-to-test

#729 fix: archive dir error
  pkg/nfs/controllerserver.go
Labels: kind/bug, size/XS, cncf-cla: yes, release-note, approved

#733 test: add default namespace in examples to fix e2e test failure
  Makefile
  deploy/example/cloning/nginx-pod-restored-cloning.yaml
  deploy/example/daemonset-nfs-ephemeral.yaml
  deploy/example/deployment.yaml
  deploy/example/nfs-provisioner/nfs-server.yaml
  deploy/example/nfs-provisioner/nginx-pod.yaml
  deploy/example/nginx-pod-inline-volume.yaml
  deploy/example/nginx-pod-nfs.yaml
  deploy/example/pvc-nfs-csi-dynamic.yaml
  deploy/example/pvc-nfs-csi-static.yaml
  deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
  deploy/example/statefulset.yaml
  hack/verify-examples.sh
Labels: kind/failing-test, size/S, release-note-none, cncf-cla: yes, approved

#734 fix: upgrade csi-provisioner to v5.0.2 to fix pv deletion stuck issue
  charts/README.md
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, release-note, approved

#735 fix: archive dir error#2
  pkg/nfs/controllerserver.go
  pkg/nfs/utils.go
  pkg/nfs/utils_test.go
Labels: kind/bug, size/M, cncf-cla: yes, release-note, approved

#743 fix: bump mount-utils to treat ENODEV error as corrupted mount
  go.mod
  go.sum
  vendor/k8s.io/mount-utils/mount_helper_unix.go
  vendor/modules.txt
Labels: kind/bug, size/S, cncf-cla: yes, release-note, approved

#750 fix: upgrade to csi-provisioner v5.0.2 on v4.8.0 chart
  charts/v4.8.0/csi-driver-nfs-v4.8.0.tgz
  charts/v4.8.0/csi-driver-nfs/values.yaml
  cmd/nfsplugin/main.go
  deploy/v4.8.0/csi-nfs-controller.yaml
  pkg/nfs/controllerserver.go
  pkg/nfs/nfs.go
Labels: kind/bug, size/M, cncf-cla: yes, release-note, approved

#753 doc: add support doc
  support.md
Labels: size/S, release-note-none, kind/documentation, cncf-cla: yes, approved
