Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2025-04, with the labels that each got.

#895 chore: use go1.24
  .github/workflows/static.yaml
  go.mod
  pkg/nfs/controllerserver.go
  pkg/nfs/controllerserver_test.go
  pkg/nfs/utils.go
  pkg/nfs/utils_test.go
  release-tools/prow.sh
Labels: size/M, release-note-none, cncf-cla: yes, approved

#902 test: fix CVE-2025-22871 in trivy action
  .github/workflows/trivy.yaml
Labels: kind/failing-test, size/XS, release-note-none, cncf-cla: yes, approved

#903 chore: upgrade resizer sidecar image version to v1.13.2
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/values.yaml
  deploy/csi-nfs-controller.yaml
Labels: kind/feature, size/XS, release-note-none, cncf-cla: yes, approved

#901 feat: add POD_NAMESPACE environment var
  deploy/csi-nfs-controller.yaml
  deploy/csi-snapshot-controller.yaml
Labels: kind/feature, size/S, lgtm, release-note-none, cncf-cla: yes, approved, ok-to-test
