Repository kubernetes-csi/csi-driver-nfs, pull requests merged in 2025-02, with the labels that each got.

#857 test: fix CVE-2025-22866 in trivy action
  .github/workflows/trivy.yaml
Labels: kind/failing-test, size/XS, release-note-none, cncf-cla: yes, approved

#859 fix: ondelete config no assigne
  pkg/nfs/nfs.go
Labels: kind/bug, size/XS, lgtm, cncf-cla: yes, release-note, approved, ok-to-test

#860 fix: incorrect affinity chart config
  charts/latest/csi-driver-nfs-v0.0.0.tgz
  charts/latest/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/latest/csi-driver-nfs/templates/csi-snapshot-controller.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, release-note, approved

#862 fix: incorrect affinity chart config in v4.10.0 chart
  charts/v4.10.0/csi-driver-nfs-v4.10.0.tgz
  charts/v4.10.0/csi-driver-nfs/templates/csi-nfs-controller.yaml
  charts/v4.10.0/csi-driver-nfs/templates/csi-snapshot-controller.yaml
Labels: kind/bug, size/XS, cncf-cla: yes, release-note, approved

#868 chore: update csi release tools (building driver with go1.23.6)
  release-tools/prow.sh
Labels: kind/feature, size/XS, release-note-none, cncf-cla: yes, approved
